image: ruby:2.7

stages:
  - preview
  - deploy
  - notify

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/ruby

before_script:
  - bundle install --without nanoc -j $(nproc) --path vendor/ruby
  - bundle exec nanoc
  - bundle exec nanoc check --deploy

preview:
  stage: preview
  variables:
    NETLIFY_SITE_ID: $NETLIFY_SITE_ID
    NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN
    GITLAB_API_TOKEN: $GITLAB_API_TOKEN
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - vendor/ruby
      - .npm/
  script:
    - curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
    - apt-get install -y nodejs curl jq
    - npm ci --cache .npm --prefer-offline
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir output | tee netlify_output.txt
    - export DRAFT_URL=$(cat netlify_output.txt | grep 'Draft.*https' | sed -e 's/\x1b\[[0-9;]*m//g' | awk -F " " '{print $NF}')
      #Edit MR description with a link to latest preview
    - 'curl
        --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN"
        "https://crypt.cybrilla.io/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID" > mr.json'
    - export DESCRIPTION=$(jq -r '.description' mr.json)
    - 'if [[ $DESCRIPTION != *"Browse the Preview"* ]];
      then
        export DESCRIPTION=$(echo "$DESCRIPTION 

                                    
                                  😎 **Browse the Preview: $DRAFT_URL**");
      else
        export DESCRIPTION=$(echo $DESCRIPTION | sed "s~\*\*Browse the Preview: https://.*\*\*~\*\*Browse the Preview: $DRAFT_URL\*\*~g");
      fi'
    - 'curl --request PUT
        --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN"
        --data "description=$DESCRIPTION"
        "https://crypt.cybrilla.io/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID"'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  tags:
    - preview

deploy:
  stage: deploy
  variables:
    AWS_DEFAULT_REGION: $PROD_AWS_DEFAULT_REGION
    AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
    AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
  script:
    - apt install unzip
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - echo "$AWS_DEFAULT_REGION"
    - aws s3 sync --delete output s3://prod-product-docs
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      changes:
        - content/**/*
        - nanoc.yaml
  tags:
    - deploy

notify:
  stage: notify
  variables:
    MATTERMOST_WEBHOOK: $MATTERMOST_WEBHOOK
  script:
    - apt update -y
    - apt install -y jq
    - 'curl --request GET
        --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN"
        "https://crypt.cybrilla.io/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHORT_SHA/merge_requests" > mr.json'
    - export MERGE_REQUEST_ID="$(cat mr.json | jq -r '.[] | .iid')"
    - export TITLE="$(cat mr.json | jq -r '.[] | .title')"
    - export DESCRIPTION="$(cat mr.json | jq -r '.[] | .description' | awk -F"😎" '{print $1}' | awk -F" *\*\*Browse the Preview" '{print $1}' | awk -F"\*\*Browse the Preview" '{print $1}')"
    - if [[ -z "$DESCRIPTION" ]]; then export DESCRIPTION="$(cat mr.json | jq -r '.[] | .description' | awk -F"netlify.app\*\* *" '{print $2}')"; fi
    - if [[ ! -z "$DESCRIPTION" ]]; then export DESCRIPTION="\n \`\`\`\n$DESCRIPTION\n\`\`\`"; fi
    - if [[ -z "$DESCRIPTION" ]]; then export DESCRIPTION=""; fi
    - export AUTHOR="$(cat mr.json | jq -r '.[] | .author | .name')"
    - export MERGER="$(cat mr.json | jq -r '.[] | .merged_by | .name')"
    - 'curl -i -X POST -H "Content-Type: application/json" -d "{\"text\":\"[Product Docs: $TITLE](https://crypt.cybrilla.io/fintechprimitives/docs/-/merge_requests/$MERGE_REQUEST_ID) (created by $AUTHOR and published by $MERGER)$DESCRIPTION\"}" $MATTERMOST_WEBHOOK;'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      changes:
        - content/**/*
        - nanoc.yaml
  tags:
    - notify
